# Generated by Django 4.1 on 2022-08-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDept',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('student_dept', models.CharField(blank=True, max_length=45, null=True)),
                ('campus', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'student_dept',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('student_dept', models.CharField(max_length=45)),
                ('student_name', models.CharField(blank=True, max_length=45, null=True)),
                ('student_address', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'students',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Userrole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_address', models.CharField(blank=True, max_length=255, null=True)),
                ('user_role', models.CharField(blank=True, max_length=255, null=True)),
                ('userid', models.IntegerField()),
            ],
            options={
                'db_table': 'userrole',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.IntegerField(primary_key=True, serialize=False)),
                ('age', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
